name: Clear Database

on:
  workflow_dispatch:

jobs:
  clear-db:
    runs-on: self-hosted

    steps:
      - name: Clear SQLite Database
        run: docker exec job_fetching_agent_api python clear_db.py
