name: Deploy to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted #because I deploy it on my home server, which I connected in GitHub actions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> .env
          echo "LANGFUSE_SECRET_KEY=${{ secrets.LANGFUSE_SECRET_KEY }}" >> .env
          echo "LANGFUSE_PUBLIC_KEY=${{ secrets.LANGFUSE_PUBLIC_KEY }}" >> .env
          echo "LANGFUSE_HOST=${{ secrets.LANGFUSE_HOST }}" >> .env
          echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> .env
          echo "MATCH_THRESHOLD=${{ secrets.MATCH_THRESHOLD }}" >> .env
          echo "CLOUDFLARE_TUNNEL_TOKEN=${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}" >> .env

      - name: Build and Start Docker Containers
        run: |
          docker-compose down
          docker-compose up -d --build

      - name: Clean up old Docker images (optional but recommended)
        run: docker image prune -f
