name: Scheduled Job Fetcher

on:
  schedule:
    # runs every day at 9:00 AM UTC
    - cron: '0 9 * * *'
    
  # Allows you to manually trigger it from the GitHub Actions tab
  workflow_dispatch: 

jobs:
  run-scraper:
    runs-on: self-hosted

    steps:
      - name: Run Job Scraper Script in Docker
        run: docker exec job_fetching_agent_api python run_job_scraper.py
